# ---------------------------------------------------------------------------------------
#  Your basic info
# ---------------------------------------------------------------------------------------
base_info:
  title: VirtualHotBarの博客
  author: VirtualHotBar # Author name
  url: https://www.loser.plus # Site url
  # Logo image (You can use local image, image external link or don’t fill)
  logo_img: /favicon.ico # logo image on the left of the navigation bar

# ---------------------------------------------------------------------------------------
# Theme style settings
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: "#E8608D"

  # Avatar (You can use local image or image external link)
  avatar: /favicon.ico # avatar of the author

  # Favicon (You can use local image or image external link)
  favicon: /favicon.ico # favicon of the site

  # Article image align position
  article_img_align: center # value: left | center

  # Left side width
  left_side_width: 240px #sidebar width, for toc

  # Content area max width
  content_max_width: 960px #content max width, for article

  #navigation bar background color (from left to right)
  nav_color: 
    left: "#f78736" #left side 
    right: "#367df7"  #right side
    transparency: 35 #percent (10-99)

  # Mouse hover
  hover:
    shadow: true # shadow effect when the mouse hover
    scale: false # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: true
    background_image:
      light: https://www.hotpe.top/API/RandomPic/MC # background image of the first screen, use relative path or external link (if your website is in subdirectory, use external link)
      dark: https://www.hotpe.top/API/RandomPic/MC # background image of the first screen, use relative path or external link (if your website is in subdirectory, use external link)
    title_color:
      light: "#fff" # first screen title color (light mode)
      dark: "#323739" # first screen title color (dark mode)
    description: "最聪明的处世术是，既对世俗投以白眼，又与其同流合污。" # the title in the middle of the first screen

  # Scroll style settings
  scroll:
    progress_bar: # reading progress bar
      enable: true 
    percent: # reading progress percent
      enable: false

# ---------------------------------------------------------------------------------------
# Social contact link
# ---------------------------------------------------------------------------------------
social_contact: # social contact icons in the first screen, you can add more by using fontawesome icon names
  enable: true
  links:
    github: "https://github.com/VirtualHotBar" # your GitHub URL
    instagram: # your Instagram URL
    zhihu:  # your ZhiHu URL
    twitter:  # your twitter URL
    email: "hotbar@hotpe.top" # your email
    bilibili: "https://space.bilibili.com/443230923"
    qq: "https://wpa.qq.com/msgrd?v=3&uin=3143771718&site=qq&menu=yes"
    # ...... # you can add more

# ---------------------------------------------------------------------------------------
# Navigation menu
# ---------------------------------------------------------------------------------------
menu: #you can customize
  Home: /
  Archives: /archives
  Categories: /categories
  "投喂": /donation
  Links: /links
  About: /about

# ---------------------------------------------------------------------------------------
# Home page article block display settings
# ---------------------------------------------------------------------------------------
home_article:
  category:
    enable: true # show category in home page article block
    limit: 3 # max number of categories shown in home page article block
  tag:
    enable: true # show tags in home page article block
    limit: 3 # max number of tags shown in home page article block

# ---------------------------------------------------------------------------------------
# Post page Settings
# ---------------------------------------------------------------------------------------
post:
  # Post word count
  # Dependencies: hexo-wordcount (npm install hexo-wordcount)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    enable: true
    wordcount: true # word count, one article
    min2read: true # time to read, one article

  # Author label
  author_label:
    enable: true
    auto: false # if true, show Lv1, Lv2, Lv3... , If false, show custom label
    # label array item can be one or more
    custom_label_list: ["博主"]

# ---------------------------------------------------------------------------------------
# Code copy
# ---------------------------------------------------------------------------------------
code_copy:
  enable: true

# ---------------------------------------------------------------------------------------
# Table of Contents in the Sidebar
# ---------------------------------------------------------------------------------------
toc:
  enable: true

  # Automatically add list number to toc.
  number: false

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true

  # If true, open TOC every time when you enter the article page
  init_open: true

# ---------------------------------------------------------------------------------------
# Post copyright info
# ---------------------------------------------------------------------------------------
copyright_info:
  enable: true

# ---------------------------------------------------------------------------------------
# Website count
# ---------------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: true
    site_pv: true
    page_pv: true

# ---------------------------------------------------------------------------------------
# Local Search
# Dependencies: hexo-generator-searchdb
# See: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search:
  enable: true
  preload: true # Preload the search data when the page loads

# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------
comment:
  enable: true
  use: twikoo # values: waline | gitalk | twikoo

  # Waline
  # See: https://waline.js.org/guide/get-started.html
  waline:
    serverUrl:  # Waline server url(vercel) example: https://example.example.com
    lang: zh-CN # Waline language, default: zh-CN. See: https://waline.js.org/guide/client/i18n.html
    dark: auto # Waline dark mode, default: auto. See: https://waline.js.org/reference/component.html#dark
  
  # Gitalk
  # See: https://github.com/gitalk/gitalk
  gitalk:
    github_id: # GitHub repo owner
    repository: # Repository name to store issues
    client_id: # GitHub Application Client ID
    client_secret: # GitHub Application Client Secret

  # Twikoo
  # See: https://github.com/imaegoo/twikoo
  twikoo:
    visitor: true
    env_id: "https://twikoo.hotpe.top/"# Vercel or Tencent Cloud Function environment ID
    region: # environment region. If select Guangzhou, fill in "ap-guangzhou". (optional)

# ---------------------------------------------------------------------------------------
# RSS
# Dependencies: hexo-generator-feed
# See: https://github.com/hexojs/hexo-generator-feed
# ---------------------------------------------------------------------------------------
rss:
  enable: false

# ---------------------------------------------------------------------------------------
# Lazyload image
# ---------------------------------------------------------------------------------------
lazyload:
  enable: true

# ---------------------------------------------------------------------------------------
# CDN
# ---------------------------------------------------------------------------------------
cdn:
  enable: false

# ---------------------------------------------------------------------------------------
# PJAX
# ---------------------------------------------------------------------------------------
pjax:
  enable: true

# ---------------------------------------------------------------------------------------
# Footer settings
# ---------------------------------------------------------------------------------------
footer: 
  upyun: "https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral"
  since: 2019 # the starting year of your website, Can be null
  runtime: true
  icp: 蜀ICP备2023001640号  # ICP record number of your website, Can be null

# ---------------------------------------------------------------------------------------
# Redefine Theme version (Please don't modify)
# ---------------------------------------------------------------------------------------
version: 0.3.4

# Search
## See: https://github.com/theme-next/hexo-generator-searchdb
search:
  path: search.json
  field: post
  content: true
  format: striptags
